"""add sop review events

Revision ID: 23c94ebddde8
Revises: 74eff825b4fc
Create Date: 2026-09-22 17:02:18.883638
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "23c94ebddde8"
down_revision: str | None = "74eff825b4fc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sop_revision_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sop_version_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column(
            "old_status",
            sa.Enum(
                "DRAFT",
                "AI_EXTRACTED",
                "IN_REVIEW",
                "APPROVED",
                "PUBLISHED",
                "RETIRED",
                name="sopstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "DRAFT",
                "AI_EXTRACTED",
                "IN_REVIEW",
                "APPROVED",
                "PUBLISHED",
                "RETIRED",
                name="sopstatus",
            ),
            nullable=False,
        ),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sop_version_id"],
            ["sop_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sop_revision_events_event_type"),
        "sop_revision_events",
        ["event_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_sop_revision_events_sop_version_id"),
        "sop_revision_events",
        ["sop_version_id"],
        unique=False,
    )
    with op.batch_alter_table("sop_versions") as batch_op:
        batch_op.create_unique_constraint("uq_sop_version", ["sop_id", "version"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sop_versions") as batch_op:
        batch_op.drop_constraint("uq_sop_version", type_="unique")
    op.drop_index(op.f("ix_sop_revision_events_sop_version_id"), table_name="sop_revision_events")
    op.drop_index(op.f("ix_sop_revision_events_event_type"), table_name="sop_revision_events")
    op.drop_table("sop_revision_events")
    # ### end Alembic commands ###
