"""create core audit tables

Revision ID: 74eff825b4fc
Revises:
Create Date: 2026-09-22 16:56:07.079748
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "74eff825b4fc"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "documents",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=100), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("storage_key", sa.String(length=500), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("storage_key"),
    )
    op.create_index(op.f("ix_documents_sha256"), "documents", ["sha256"], unique=True)
    op.create_table(
        "sops",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("product_code", sa.String(length=100), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sops_code"), "sops", ["code"], unique=True)
    op.create_index(op.f("ix_sops_product_code"), "sops", ["product_code"], unique=False)
    op.create_table(
        "sop_versions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sop_id", sa.String(length=36), nullable=False),
        sa.Column("source_document_id", sa.String(length=36), nullable=True),
        sa.Column("version", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "DRAFT",
                "AI_EXTRACTED",
                "IN_REVIEW",
                "APPROVED",
                "PUBLISHED",
                "RETIRED",
                name="sopstatus",
            ),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sop_id"],
            ["sops.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_document_id"],
            ["documents.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sop_versions_sop_id"), "sop_versions", ["sop_id"], unique=False)
    op.create_table(
        "sop_steps",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("sop_version_id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("required", sa.Boolean(), nullable=False),
        sa.Column("preconditions", sa.JSON(), nullable=False),
        sa.Column("evidence_requirements", sa.JSON(), nullable=False),
        sa.Column("on_missing", sa.String(length=50), nullable=False),
        sa.Column("source_refs", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sop_version_id"],
            ["sop_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sop_steps_sop_version_id"), "sop_steps", ["sop_version_id"], unique=False
    )
    op.create_table(
        "work_orders",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("code", sa.String(length=100), nullable=False),
        sa.Column("product_code", sa.String(length=100), nullable=False),
        sa.Column("sop_version_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "CREATED",
                "INSPECTING",
                "VERIFIED",
                "EXCEPTION_PENDING",
                "MANUAL_REVIEW",
                "EXCEPTION_CONFIRMED",
                "EXCEPTION_REJECTED",
                "REWORK_ASSIGNED",
                "REWORK_SUBMITTED",
                "REWORK_REVIEW",
                "RELEASED",
                "ARCHIVED",
                name="workorderstatus",
            ),
            nullable=False,
        ),
        sa.Column("current_assignee", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["sop_version_id"],
            ["sop_versions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_work_orders_code"), "work_orders", ["code"], unique=True)
    op.create_index(
        op.f("ix_work_orders_product_code"), "work_orders", ["product_code"], unique=False
    )
    op.create_index(
        op.f("ix_work_orders_sop_version_id"), "work_orders", ["sop_version_id"], unique=False
    )
    op.create_index(op.f("ix_work_orders_status"), "work_orders", ["status"], unique=False)
    op.create_table(
        "audit_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("work_order_id", sa.String(length=36), nullable=False),
        sa.Column("event_type", sa.String(length=100), nullable=False),
        sa.Column("actor_id", sa.String(length=100), nullable=False),
        sa.Column(
            "old_status",
            sa.Enum(
                "CREATED",
                "INSPECTING",
                "VERIFIED",
                "EXCEPTION_PENDING",
                "MANUAL_REVIEW",
                "EXCEPTION_CONFIRMED",
                "EXCEPTION_REJECTED",
                "REWORK_ASSIGNED",
                "REWORK_SUBMITTED",
                "REWORK_REVIEW",
                "RELEASED",
                "ARCHIVED",
                name="workorderstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "new_status",
            sa.Enum(
                "CREATED",
                "INSPECTING",
                "VERIFIED",
                "EXCEPTION_PENDING",
                "MANUAL_REVIEW",
                "EXCEPTION_CONFIRMED",
                "EXCEPTION_REJECTED",
                "REWORK_ASSIGNED",
                "REWORK_SUBMITTED",
                "REWORK_REVIEW",
                "RELEASED",
                "ARCHIVED",
                name="workorderstatus",
            ),
            nullable=False,
        ),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["work_order_id"],
            ["work_orders.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_work_order_id"), "audit_events", ["work_order_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_events_work_order_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_work_orders_status"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_sop_version_id"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_product_code"), table_name="work_orders")
    op.drop_index(op.f("ix_work_orders_code"), table_name="work_orders")
    op.drop_table("work_orders")
    op.drop_index(op.f("ix_sop_steps_sop_version_id"), table_name="sop_steps")
    op.drop_table("sop_steps")
    op.drop_index(op.f("ix_sop_versions_sop_id"), table_name="sop_versions")
    op.drop_table("sop_versions")
    op.drop_index(op.f("ix_sops_product_code"), table_name="sops")
    op.drop_index(op.f("ix_sops_code"), table_name="sops")
    op.drop_table("sops")
    op.drop_index(op.f("ix_documents_sha256"), table_name="documents")
    op.drop_table("documents")
    # ### end Alembic commands ###
